export interface GalleryProject {
  slug: string;
  title: string;
  category: string;
  categorySlug: string;
  location: string;
  description: string;
  scope: string[];
  image?: string;
  imagePosition?: string;
}

export const PROJECT_CATEGORIES = [
  { label: "All", slug: "all" },
  { label: "Remodels", slug: "complete-remodel" },
  { label: "Foundations", slug: "concrete-foundations" },
  { label: "Retaining Walls", slug: "retaining-walls" },
  { label: "Decks", slug: "composite-decks" },
  { label: "Roofing", slug: "roofing" },
  { label: "ADUs", slug: "adu-construction" },
];

export const GALLERY_PROJECTS: GalleryProject[] = [
  {
    slug: "noe-valley-kitchen-remodel",
    title: "Modern Kitchen Remodel — White Cabinets & Quartz",
    category: "Complete Remodel",
    categorySlug: "complete-remodel",
    location: "Bay Area",
    description: "Full kitchen remodel with flat-panel white cabinetry, quartz countertops, stainless steel appliances, recessed LED lighting, and luxury vinyl plank flooring — bright, clean, and built for daily life.",
    scope: ["Flat-panel white cabinetry", "Quartz countertops", "Stainless steel appliances", "Recessed LED lighting", "Luxury vinyl plank flooring"],
    image: "/images/gallery-remodel-kitchen.jpg",
  },
  {
    slug: "bay-area-kitchen-remodel-island",
    title: "Open-Concept Kitchen — Butcher Block Island & Exposed Beams",
    category: "Complete Remodel",
    categorySlug: "complete-remodel",
    location: "Bay Area",
    description: "Full kitchen remodel with white shaker cabinetry, butcher block waterfall island with seating, exposed wood ceiling beams, linear pendant lighting, and stainless steel appliances — a modern farmhouse feel built for everyday cooking and entertaining.",
    scope: ["White shaker cabinetry", "Butcher block waterfall island", "Exposed beam ceiling detail", "Linear pendant lighting", "Stainless steel appliances"],
    image: "/images/gallery-remodel-kitchen-island.jpg",
  },
  {
    slug: "bay-area-bathroom-remodel",
    title: "Modern Bathroom Remodel — Marble Tile & Glass Shower",
    category: "Complete Remodel",
    categorySlug: "complete-remodel",
    location: "Bay Area",
    description: "Full bathroom remodel with gray marble floor and shower tile, sliding glass shower door, white shaker vanity with marble top, floating wood shelves, and modern sconce lighting — clean and functional.",
    scope: ["Gray marble tile flooring", "Sliding glass shower enclosure", "White shaker vanity", "Floating wood shelves", "Modern sconce lighting"],
    image: "/images/gallery-remodel-bathroom.jpg",
    imagePosition: "center 70%",
  },
  {
    slug: "bernal-heights-foundation",
    title: "New Foundation & Rebar Layout",
    category: "Concrete Foundations",
    categorySlug: "concrete-foundations",
    location: "Bay Area",
    description: "Laid out a reinforced rebar grid for a new concrete foundation alongside an existing home — precision-tied rebar with proper spacing, formwork, and string lines set for a clean pour.",
    scope: ["Rebar grid layout", "Form & string-line setup", "Foundation pour prep", "Permit & inspection", "5-year warranty"],
    image: "/images/gallery-foundation-rebar.jpg",
  },
  {
    slug: "bay-area-concrete-slab-pour",
    title: "Residential Concrete Slab — Rebar & Formwork",
    category: "Concrete Foundations",
    categorySlug: "concrete-foundations",
    location: "Bay Area",
    description: "Prepped and formed a new residential concrete slab with a welded rebar grid on chairs for proper clearance, 2×6 perimeter formwork staked and leveled, and compacted subgrade — ready for a clean same-day pour.",
    scope: ["Rebar grid on chairs", "2×6 perimeter formwork", "Subgrade compaction", "Same-day concrete pour", "Finish & cure"],
    image: "/images/gallery-foundation-slab-prep.jpg",
  },
  {
    slug: "twin-peaks-retaining-wall",
    title: "Concrete Retaining Wall with Redwood Staircase",
    category: "Retaining Walls",
    categorySlug: "retaining-walls",
    location: "Twin Peaks, San Francisco",
    description: "Built a poured concrete retaining wall with an integrated redwood staircase, herringbone paver walkway, and drought-tolerant landscaping — turning a steep grade change into a functional, finished backyard.",
    scope: ["Poured concrete retaining wall", "Redwood stair integration", "Paver walkway", "Drought-tolerant landscaping", "Drainage provisions"],
    image: "/images/gallery-retaining-wall-steps.jpg",
  },
  {
    slug: "mill-valley-hillside-wall",
    title: "Concrete Wall with Fence & Landscape",
    category: "Retaining Walls",
    categorySlug: "retaining-walls",
    location: "Mill Valley",
    description: "Poured a smooth-finish concrete retaining wall topped with a redwood and steel fence for privacy, with a gravel pathway and drought-tolerant plantings along the base — clean, low-maintenance hillside solution.",
    scope: ["Smooth-finish concrete wall", "Redwood & steel fence cap", "Gravel pathway", "Drought-tolerant plantings", "River rock borders"],
    image: "/images/gallery-retaining-wall-landscaped.jpg",
  },
  {
    slug: "san-rafael-hillside-retaining-wall",
    title: "Hillside Retaining Wall — Rebar & Formwork",
    category: "Retaining Walls",
    categorySlug: "retaining-walls",
    location: "San Rafael",
    description: "Formed and reinforced a new concrete retaining wall on a steep Marin hillside — rebar grid tied to a poured footing with drainage provisions behind the wall to handle seasonal runoff.",
    scope: ["Rebar grid reinforcement", "Wood formwork", "Poured concrete footing", "Behind-wall drainage", "Hillside erosion control"],
    image: "/images/gallery-retaining-wall-rebar.jpg",
  },
  {
    slug: "bay-area-pergola-deck",
    title: "Outdoor Living Deck with Pergola & Lighting",
    category: "Composite Decks",
    categorySlug: "composite-decks",
    location: "Bay Area",
    description: "Designed and built a multi-level composite deck with a modern louvered pergola, integrated LED step lighting, and a dedicated dining area — transforming a plain backyard into a year-round outdoor living space.",
    scope: ["Multi-level composite decking", "Modern louvered pergola", "Integrated LED step & soffit lighting", "Outdoor dining area", "Fire pit zone"],
    image: "/images/gallery-composite-deck-pergola.jpg",
  },
  {
    slug: "bay-area-spa-deck",
    title: "Evening Spa Deck with Custom Lighting",
    category: "Composite Decks",
    categorySlug: "composite-decks",
    location: "Bay Area",
    description: "Built a backyard spa retreat featuring a cedar hot tub platform, hardwood composite decking with recessed LED lighting, decorative privacy screens, and a raised planter bed — designed for year-round evening entertaining.",
    scope: ["Composite & hardwood decking", "Cedar hot tub platform", "Recessed LED pathway lighting", "Decorative metal privacy screens", "Raised planter beds"],
    image: "/images/gallery-composite-deck-spa.jpg",
  },
  {
    slug: "bay-area-wraparound-deck",
    title: "Wraparound Composite Deck with Garden View",
    category: "Composite Decks",
    categorySlug: "composite-decks",
    location: "Bay Area",
    description: "Installed a gray composite wraparound deck with white post-and-rail system, black aluminum balusters, and a staircase leading to a landscaped backyard — low-maintenance decking built for years of outdoor enjoyment.",
    scope: ["Gray composite decking", "White post & rail system", "Black aluminum balusters", "Wraparound layout", "Staircase to yard"],
    image: "/images/gallery-composite-deck-railing.jpg",
  },
  {
    slug: "bay-area-firepit-deck",
    title: "Entertainer's Deck with Fire Pit & Pergola",
    category: "Composite Decks",
    categorySlug: "composite-decks",
    location: "Bay Area",
    description: "Built a spacious gray composite deck designed for outdoor entertaining — featuring a modern fire pit, patio heater, lounge seating area, built-in BBQ zone under a steel pergola, and lush perimeter landscaping for privacy.",
    scope: ["Gray composite decking", "Oval fire pit with bench seating", "Steel pergola with BBQ zone", "Patio heater integration", "Privacy landscaping"],
    image: "/images/gallery-composite-deck-firepit.jpg",
  },
  {
    slug: "richmond-roof-replacement",
    title: "Complete Re-Roof with Architectural Shingles",
    category: "Roofing",
    categorySlug: "roofing",
    location: "Bay Area",
    description: "Full tear-off and re-roof on a modern home with a multi-angle roofline — new architectural shingles, ridge vents, skylights preserved, and clean valley flashing throughout.",
    scope: ["Full tear-off & re-roof", "Architectural shingles", "Ridge vent installation", "Skylight flashing", "Title 24 compliant"],
    image: "/images/gallery-roofing-shingles.jpg",
  },
  {
    slug: "berkeley-backyard-adu",
    title: "Backyard Studio ADU",
    category: "ADU Construction",
    categorySlug: "adu-construction",
    location: "Berkeley",
    description: "Designed and built a 600 sq ft detached ADU with full kitchen, bathroom, and private entrance — permitted through Berkeley's building department with green building compliance.",
    scope: ["Custom architectural design", "Full kitchen & bathroom", "Private entrance & patio", "Green building compliance", "Certificate of Occupancy"],
    image: "/images/gallery-adu-insulation.jpg",
  },
  {
    slug: "palo-alto-two-story-adu",
    title: "Two-Story ADU — Framing Phase",
    category: "ADU Construction",
    categorySlug: "adu-construction",
    location: "Bay Area",
    description: "Ground-up two-story ADU build — full wood framing with scaffolding, second-floor joists, and roof trusses set. Photo shows the framing phase before sheathing, with windows and doors roughed in.",
    scope: ["Two-story wood framing", "Scaffolding & safety", "Second-floor joist system", "Roof truss installation", "Window & door rough-ins"],
    image: "/images/gallery-adu-framing.jpg",
  },
  {
    slug: "san-rafael-detached-adu",
    title: "Two-Bedroom Detached ADU",
    category: "ADU Construction",
    categorySlug: "adu-construction",
    location: "San Rafael",
    description: "Built a 1,000 sq ft 2-bedroom detached ADU on a Marin hillside lot — full design-build including engineering, permits, and landscaping.",
    scope: ["1,000 sq ft 2BR/1BA", "Hillside pier foundation", "Full mechanical systems", "Landscaping & fencing", "DBI permits & C of O"],
    image: "/images/gallery-adu-housewrap.jpg",
  },
  {
    slug: "bay-area-garage-foundation-prep",
    title: "Garage Foundation — Subgrade Compaction",
    category: "Concrete Foundations",
    categorySlug: "concrete-foundations",
    location: "Bay Area",
    description: "Prepped a garage floor for a new concrete slab pour — crew ran a plate compactor over crushed gravel subgrade to achieve proper density before setting rebar and forms. Brick back wall and existing structure preserved during the rebuild.",
    scope: ["Crushed gravel subgrade", "Plate compactor densification", "Garage slab prep", "Existing structure preservation", "Concrete pour ready"],
    image: "/images/gallery-foundation-garage-prep.jpg",
  },
];
