export const SERVICE_PRICING: Record<string, { service: string; range: string; note?: string }[]> = {
  "concrete-foundations": [
    { service: "Crack Repair", range: "$3,000–$5,000", note: "Depending on severity and access" },
    { service: "Seismic Bolting", range: "$5,000–$15,000", note: "Foundation-to-frame anchoring" },
    { service: "Cripple Wall Bracing", range: "$5,000–$15,000", note: "May qualify for Brace + Bolt grant" },
    { service: "Full Foundation Replacement", range: "$30,000–$100,000+", note: "Based on home size and site conditions" },
    { service: "Concrete Flatwork (driveway/patio)", range: "$8,000–$25,000", note: "Based on square footage and finish" },
  ],
  "retaining-walls": [
    { service: "Standard CMU Block Wall (per linear ft)", range: "$200–$400", note: "4-foot height, including drainage" },
    { service: "Poured Concrete Wall (per linear ft)", range: "$300–$500", note: "Engineered, reinforced" },
    { service: "Small Retaining Wall Project", range: "$5,000–$15,000" },
    { service: "Mid-Size Hillside Wall", range: "$15,000–$40,000" },
    { service: "Complex Multi-Tier System", range: "$40,000–$80,000+", note: "Engineered terracing with drainage" },
  ],
  "complete-remodel": [
    { service: "Kitchen Remodel (mid-range)", range: "$25,000–$35,000", note: "Cabinets, counters, appliances, layout changes" },
    { service: "Kitchen Remodel (high-end)", range: "$50,000–$80,000", note: "Custom millwork, structural changes" },
    { service: "Bathroom Remodel", range: "$25,000–$75,000", note: "Full gut and rebuild" },
    { service: "Whole-Home Renovation", range: "$200–$450/sq ft", note: "Scope and finish-dependent" },
    { service: "Room Addition", range: "$600–$1,200/sq ft", note: "Including foundation and structural" },
  ],
  "composite-decks": [
    { service: "Standard Composite Deck (300 sq ft)", range: "$15,000–$35,000", note: "Including railings and permits" },
    { service: "Multi-Level Deck", range: "$35,000–$60,000+", note: "Tiered design for sloped yards" },
    { service: "Deck with Pergola", range: "$25,000–$50,000", note: "Composite deck + shade structure" },
    { service: "Railing System Only", range: "$3,000–$8,000", note: "Cable, glass, or composite rails" },
  ],
  roofing: [
    { service: "Full Re-Roof (composition shingle)", range: "$15,000–$25,000", note: "1,200–1,800 sq ft roof area" },
    { service: "Full Re-Roof (architectural shingle)", range: "$20,000–$35,000", note: "Premium materials, steep pitch" },
    { service: "Roof Repair", range: "$1,500–$8,000", note: "Leak repair, flashing, partial replacement" },
    { service: "Gutter Installation", range: "$2,000–$5,000", note: "Seamless aluminum with guards" },
    { service: "Skylight Installation", range: "$3,000–$8,000", note: "Including flashing and interior finish" },
  ],
  "exterior-repairs": [
    { service: "Dry Rot Patch (single window sill / trim piece)", range: "$800–$2,500", note: "Localized repair, no framing replacement" },
    { service: "Whole-Wall Dry Rot + Framing Replacement", range: "$4,000–$12,000", note: "Sister-framing, new sheathing, WRB, flashing" },
    { service: "Stucco Crack Patching & Spot Repair", range: "$400–$1,500", note: "Color-coat matching on existing stucco" },
    { service: "Stucco Re-Coat (one elevation)", range: "$4,000–$9,000", note: "New color coat over sound existing stucco" },
    { service: "Full Re-Stucco (whole house)", range: "$15,000–$35,000", note: "Three-coat system, new WRB and lath" },
    { service: "Hardie Board Siding (per sq ft installed)", range: "$14–$22", note: "Includes removal, flashing, and finish" },
    { service: "Wood / Cedar Siding (per sq ft installed)", range: "$10–$16", note: "Clapboard, T1-11, cedar shake, redwood" },
  ],
  "dry-rot-repair": [
    { service: "Door Frame Replacement (single)", range: "$400–$1,200", note: "Front entries, slider tracks, garage side-doors" },
    { service: "Window Sill Replacement (single)", range: "$300–$800", note: "Single-pane and dual-pane" },
    { service: "Window Full-Frame Rebuild", range: "$1,200–$3,500", note: "Sill, jamb, and casing rot" },
    { service: "Fascia Run (per linear foot)", range: "$40–$80", note: "Including soffit and freeze blocking" },
    { service: "Deck Post Replacement (per post)", range: "$600–$1,500", note: "Includes structural reconnection" },
    { service: "Beam End / Ledger Board Repair", range: "$1,500–$5,000", note: "Including hidden ledger rot" },
    { service: "Bay Window Full Structural Rebuild", range: "$8,000–$25,000", note: "Demo, sister-joist, re-sheathe, re-flash, finish" },
  ],
  "stucco-repair": [
    { service: "Hairline Crack Patch (per crack)", range: "$200–$500", note: "Color-matched and re-textured" },
    { service: "Section Re-Coat (per elevation)", range: "$1,200–$3,500", note: "New finish coat over sound existing base" },
    { service: "Full Re-Stucco — Single Elevation", range: "$4,000–$9,000", note: "Three-coat system, new lath, new WRB" },
    { service: "Whole-House Re-Stucco (1,500–2,500 sq ft)", range: "$12,000–$30,000", note: "Three-coat system, new lath, new WRB, all flashing" },
    { service: "Three-Coat New Stucco (per sq ft installed)", range: "$9–$14", note: "On new construction or full tear-off" },
    { service: "Window/Door Stucco Closure (per opening)", range: "$400–$1,200", note: "Stucco patch around new window or door installs" },
    { service: "Moisture Investigation (probe-only)", range: "$250 flat", note: "Credited toward repair if you proceed" },
  ],
  "siding-repair": [
    { service: "Single Board Replacement", range: "$200–$500", note: "T1-11, redwood, fiber cement, or matched material" },
    { service: "Section Repair (with paint match)", range: "$800–$2,500", note: "Multi-board section, pattern-matched and painted" },
    { service: "Single Wall Re-Side", range: "$4,000–$12,000", note: "Tear-off, new housewrap, flashing, new siding" },
    { service: "Whole-House Re-Side (1,800 sq ft typical)", range: "$18,000–$45,000", note: "Full tear-off, Tyvek HomeWrap, flashing inspection, new siding" },
    { service: "T1-11 Vertical Siding Installed (per sq ft)", range: "$7–$12", note: "Eichler-style and other vertical-grain installs" },
    { service: "Hardie Fiber Cement Installed (per sq ft)", range: "$14–$22", note: "Including primer, paint, and trim" },
    { service: "Asbestos Siding Removal (per sq ft)", range: "$8–$15", note: "Pre-1980 homes — certified handling and disposal" },
  ],
  "adu-construction": [
    { service: "Garage Conversion", range: "$100,000–$200,000", note: "Existing structure to finished unit" },
    { service: "Junior ADU (within home)", range: "$80,000–$150,000", note: "Up to 500 sq ft" },
    { service: "Detached ADU (studio/1BR)", range: "$200,000–$350,000", note: "New construction" },
    { service: "Detached ADU (2BR, high-end)", range: "$300,000–$450,000+", note: "Full design-build" },
    { service: "Basement Conversion", range: "$120,000–$250,000", note: "Including waterproofing and egress" },
  ],
};
